//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    DownloadTask: [
      { url: 'url 1', id: 87 },
      { url: 'url 2', id: 15 },
      { url: 'url 3', id: 6 },
      { url: 'url 4', id: 46 },
      { url: 'url 5', id: 45 },
    ],
    UserPreferences: [
      { targetFolder: 'targetFolder 1', id: 28 },
      { targetFolder: 'targetFolder 2', id: 26 },
      { targetFolder: 'targetFolder 3', id: 68 },
      { targetFolder: 'targetFolder 4', id: 21 },
      { targetFolder: 'targetFolder 5', id: 22 },
    ],
  },
};
export default data;
